### ISSUE TITLE
Add Interactivity to JSON Viewing

### ISSUE THREAD

**Issue by bibek-ranjan-saha** [foss42/apidash#11]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add interactivity so it is small and easily viewable to the users

**Describe the solution/feature you'd like us to add**
used [jsonview](https://pub.dev/packages/json_view) package incase of json and if the response is within the range

**Any other feedback you would like to provide regarding the site**
No for now

**Comment by animator** [comment]
Hi @bibek-ranjan-saha 
We looked into various packages (including jsonview) that provide JSON Views before we shipped the first release.
The major issues with these packages were customizability & performance.
We cannot switch between different views based on the response length as it may lead to confusion.
And adding this feature requires a lot more due diligence and we will have to figure out a high performant way to do so.

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant

**Comment by ashitaprasad** [comment]
Hi @MihirCharan42,
Firstly, join our [discord server](https://bit.ly/heyfoss) so that you can message on the **#foss** channel whenever you encounter any issue. That is also our official channel where we have all discussions related to API Dash & GSSoC.
You must also follow the [Contribution Guidelines](https://github.com/foss42/api-dash/blob/main/CONTRIBUTING.md).
We currently do not assign an issue to a single person, as it might deter others from solving the issue with a better approach.
Once you have a working implementation (taking into consideration the performance concerns highlighted in the issue above), feel free to send across a PR so that we can review the code.

**Comment by animator** [comment]
This issue has been resolved and merged in the main branch. 
The issue will be closed with the next release of API Dash.

**Comment by animator** [comment]
It is now available in the latest release of API Dash ⚡️
