### ISSUE TITLE
Add CodeGen for Java (Unirest)

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/apidash#135]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Java 
Library - [Unirest](https://github.com/Kong/unirest-java)

**Comment by saurav0523** [comment]
hey @ashitaprasad 
i want to work on this issue, can you please assign me

**Comment by animator** [comment]
@saurav0523 We do not assign issues. You are free to work on it and send across a PR.

**Comment by saurav0523** [comment]
@animator ok sir

**Comment by saurav0523** [comment]
@ashitaprasad can you please give me hint how should i start

**Comment by saurav0523** [comment]
@animator can you please give me hint how should i start

**Comment by ashitaprasad** [comment]
@saurav0523  To get started with API Dash codegen, check out the codes in the `lib/codegen` folder for languages that have been already implemented like python, kotlin etc. Usually implementing a codegen for a new language/library in API Dash requires:

1. Some idea of how jinja template works
2. Some idea of library/language specific client code that you are generating as the generated code should be as natural (not spaghetti) as possible for someone who is already familiar with the language/library.
3. You need to also verify the generated code and write appropriate test cases to cover the various model input scenarios.

Related Link - https://github.com/foss42/apidash/discussions/80

**Comment by tanishgl** [comment]
@ashitaprasad As suggested by Unirest docs, the code is in the form of a snippet and not a file. Since it's a maven based dependency, I guess that it'd work on the assumption that the dependency is already added in pom.xml and the snippet would be part of some service, controller etc. kind of file instead of being a standalone. And the code snippet for a simple GET request would look like this :- 
`String url = "https://api.foss42.com";`
        `return Unirest.get(url)`
                  `.asString()`
                `.getBody();`

I've created a template which would generate such snippets and tested it in a Spring project. Your insights on whether the above snippet is okay or what the right generated code should look like, would be really valuable.
