### ISSUE TITLE
Deletion of Global Environment variable causes null error

### ISSUE THREAD

**Issue by sai-phaneesh** [foss42/apidash#508]
#### Describe the bug/problem
In the environments section when an attempt is made to delete the Global environment it throws null check error in the environments panel.

#### Steps to Reproduce the bug/problem

https://github.com/user-attachments/assets/5e1f0925-d2a4-49ee-9440-3c6635268b5c

#### Expected behavior
Either the delete option for global environment should be removed/disabled.

#### Device Info (The device where you encountered this issue)
 - OS: MacOS
 - Version: Sequoia 15.0.1 

#### Flutter Doctor
```
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.94.2)
[✓] Network resources
```

**Comment by Clasherzz** [comment]
hey thats a good one @sai-phaneesh  never thought of deleting it since i always thought it was  a core functionality

**Comment by Clasherzz** [comment]
@ashitaprasad 
 **SOLUTION PROPOSED FOR THIS**  
since global enviornment is an feature  proposed under documentation  (https://github.com/foss42/apidash/blob/main/doc/user_guide/env_user_guide.md) its better to disable the delete button if the user has selected Global Env. Since there is a chance if we give them ability to delete it there won't be able to reproduce a similar feauture. This approach wouldn't involve much change of code.
